# Generated by Django 3.2.5 on 2021-07-23 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=40, verbose_name='手机名')),
                ('goods_intro', models.CharField(max_length=300, verbose_name='手机简介')),
                ('evalute_num', models.IntegerField(default=0, verbose_name='手机评价累计')),
            ],
            options={
                'verbose_name_plural': '手机信息表',
            },
        ),
        migrations.CreateModel(
            name='GoodsCapacity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_capacity', models.CharField(max_length=20, verbose_name='手机容量')),
            ],
            options={
                'verbose_name_plural': '手机储存容量表',
            },
        ),
        migrations.CreateModel(
            name='GoodsColorsPicture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_color_name', models.CharField(max_length=50, verbose_name='手机具体款式名称')),
                ('phone_picture_addr', models.CharField(max_length=200, verbose_name='手机图片地址')),
                ('goods_status', models.IntegerField(default=2, verbose_name='状态 2上架，1下架， 0待上架')),
            ],
            options={
                'verbose_name_plural': '各种手机的具体款式表',
            },
        ),
        migrations.CreateModel(
            name='GoodsSpecies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('species_name', models.CharField(max_length=50, verbose_name='手机品牌种类名称')),
            ],
            options={
                'verbose_name_plural': '手机品牌种类表',
            },
        ),
        migrations.CreateModel(
            name='SlideshowPicture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_picture_addr', models.CharField(max_length=200, verbose_name='图片地址')),
            ],
            options={
                'verbose_name_plural': '轮播图表',
            },
        ),
        migrations.CreateModel(
            name='GoodsRepertory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_num_all', models.IntegerField(verbose_name='库存总数量')),
                ('goods_price', models.IntegerField(verbose_name='手机价格')),
                ('goods_residue', models.IntegerField(verbose_name='库存剩余量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_show.goods', verbose_name='手机id(外键）')),
                ('goods_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_show.goodscapacity', verbose_name='手机容量id(外键）')),
                ('goods_colors_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_show.goodscolorspicture', verbose_name='手机颜色id外键')),
            ],
            options={
                'verbose_name_plural': '手机库存价格表',
            },
        ),
        migrations.CreateModel(
            name='GoodsDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_details_addr', models.CharField(max_length=200, verbose_name='详情地址')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_show.goods', verbose_name='手机id(外键）')),
            ],
            options={
                'verbose_name_plural': '手机详情信息表',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_show.goodsspecies', verbose_name='手机品牌外键'),
        ),
    ]
