# Generated by Django 3.2.5 on 2021-07-23 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=20, verbose_name='密码')),
                ('user_email', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='邮箱')),
                ('phone', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='手机号')),
                ('is_superuser', models.IntegerField(default=0, verbose_name='是否为管理员')),
                ('user_privilege', models.IntegerField(default=1, verbose_name='是否活着')),
            ],
            options={
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_postcode', models.CharField(max_length=20, verbose_name='收件人地址')),
                ('address_address', models.IntegerField(verbose_name='地址邮编')),
                ('address_addressee_name', models.CharField(max_length=20, verbose_name='收件人姓名')),
                ('address_address_phone', models.BigIntegerField(unique=True, verbose_name='收件人电话')),
                ('is_default_address', models.BigIntegerField(default=1, verbose_name='是否是默认地址0否，1是')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.userinfo', verbose_name='用户id')),
            ],
            options={
                'verbose_name_plural': '收件人地址信息表',
            },
        ),
    ]
