# Generated by Django 3.2.5 on 2021-07-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='my_money',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='余额(单位:￥)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_address',
            field=models.CharField(max_length=20, verbose_name='收件人地址'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_postcode',
            field=models.IntegerField(verbose_name='地址邮编'),
        ),
    ]
