# Generated by Django 3.2.5 on 2021-07-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_auto_20210723_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_default_address',
            field=models.IntegerField(default=1, verbose_name='是否是默认地址0否，1是'),
        ),
        migrations.CreateModel(
            name='RecordTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_money', models.IntegerField(verbose_name='本次花费前的余额')),
                ('recharge_or_consume', models.CharField(max_length=20, verbose_name='+充值或-消费')),
                ('next_money', models.IntegerField(verbose_name='本次花费后的余额')),
                ('is_delete_record', models.IntegerField(default=0, verbose_name='是否删除花费记录 0否，1是')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.userinfo', verbose_name='用户id')),
            ],
            options={
                'verbose_name_plural': '流水表',
            },
        ),
    ]
