# Generated by Django 3.2.5 on 2021-07-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_auto_20210723_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_address',
            new_name='addressee_address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_addressee_name',
            new_name='addressee_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_address_phone',
            new_name='addressee_phone',
        ),
    ]
