# Generated by Django 3.2.5 on 2021-07-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0006_auto_20210724_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_default_address',
            field=models.IntegerField(choices=[(0, '非默认地址'), (1, '默认地址')], default=0, verbose_name='是否是默认地址0否，1是'),
        ),
    ]
