# Generated by Django 3.2.5 on 2021-07-23 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_register', '0002_auto_20210723_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goodsid', models.CharField(max_length=50, verbose_name='手机名')),
                ('colorid', models.CharField(max_length=150, verbose_name='手机颜色')),
                ('capacityid', models.CharField(max_length=10, verbose_name='手机存储容量')),
                ('buy_count', models.IntegerField(default=1, verbose_name='购买件数')),
                ('is_default_address', models.BigIntegerField(default=0, verbose_name='是否删除1 删除 ， 0不删除')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.userinfo', verbose_name='用户id')),
            ],
            options={
                'verbose_name_plural': '购物车',
            },
        ),
    ]
