# Generated by Django 3.2.5 on 2021-07-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_alter_shoppingcart_is_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='color_name',
            field=models.CharField(default='无', max_length=50, verbose_name='手机颜色'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='intro',
            field=models.CharField(default='手机', max_length=300, verbose_name='手机简介'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='price',
            field=models.IntegerField(default=0, verbose_name='手机价格'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='colorid',
            field=models.CharField(max_length=200, verbose_name='手机颜色图片地址'),
        ),
    ]
