# Generated by Django 3.2.5 on 2021-07-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_auto_20210726_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='shop_id',
            field=models.IntegerField(default=0, verbose_name='手机id'),
        ),
    ]
