# Generated by Django 3.2.5 on 2021-07-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingorderinfo',
            name='is_default_address',
            field=models.IntegerField(default=0, verbose_name='是否删除订单信息，1 删除 ， 0不删除'),
        ),
    ]
