# Generated by Django 3.2.5 on 2021-07-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_order', '0002_alter_shoppingorderinfo_is_default_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingorderinfo',
            name='order_num',
        ),
        migrations.AddField(
            model_name='shoppingorderdetail',
            name='color_name',
            field=models.CharField(default='无', max_length=50, verbose_name='手机颜色'),
        ),
        migrations.AddField(
            model_name='shoppingorderdetail',
            name='intro',
            field=models.CharField(default='手机', max_length=300, verbose_name='手机简介'),
        ),
        migrations.AddField(
            model_name='shoppingorderdetail',
            name='price',
            field=models.IntegerField(default=0, verbose_name='手机价格'),
        ),
        migrations.AddField(
            model_name='shoppingorderdetail',
            name='price_all',
            field=models.IntegerField(default=0, verbose_name='单样手机总价'),
        ),
        migrations.AddField(
            model_name='shoppingorderdetail',
            name='shop_id',
            field=models.IntegerField(default=0, verbose_name='手机id'),
        ),
    ]
