# Generated by Django 3.2.5 on 2021-07-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_order', '0003_auto_20210726_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingorderdetail',
            name='colorid',
            field=models.CharField(max_length=150, verbose_name='手机图片地址'),
        ),
        migrations.AlterField(
            model_name='shoppingorderinfo',
            name='is_default_address',
            field=models.IntegerField(choices=[(0, '不删除'), (1, '删除')], default=0, verbose_name='是否删除订单信息，1 删除 ， 0不删除'),
        ),
        migrations.AlterField(
            model_name='shoppingorderinfo',
            name='is_trade',
            field=models.IntegerField(choices=[(0, '购买'), (1, '不买了')], default=0, verbose_name='是否交易, 1 购买 2 不买了'),
        ),
        migrations.AlterField(
            model_name='shoppingorderinfo',
            name='payment',
            field=models.IntegerField(choices=[(0, '余额'), (1, '微信'), (2, '支付宝')], default=0, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='shoppingorderinfo',
            name='payment_static',
            field=models.IntegerField(choices=[(0, '待支付'), (1, '已支付')], default=0, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='shoppingorderinfo',
            name='trade_money',
            field=models.IntegerField(default=0, verbose_name='交易金额'),
        ),
    ]
