# Generated by Django 3.2.5 on 2021-07-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_order', '0004_auto_20210726_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingorderinfo',
            name='address',
        ),
        migrations.AlterField(
            model_name='shoppingorderinfo',
            name='is_trade',
            field=models.IntegerField(choices=[(0, '购买'), (1, '不买了')], default=0, verbose_name='是否交易, 0 购买 1 不买了'),
        ),
        migrations.AlterField(
            model_name='shoppingorderinfo',
            name='payment',
            field=models.IntegerField(choices=[(0, '余额'), (1, '微信'), (2, '支付宝')], default=0, verbose_name='支付方式 0余额 1微信 2支付宝'),
        ),
        migrations.AlterField(
            model_name='shoppingorderinfo',
            name='payment_static',
            field=models.IntegerField(choices=[(0, '待支付'), (1, '已支付')], default=0, verbose_name='支付状态 0待支付 1已支付'),
        ),
    ]
