# Generated by Django 3.2.5 on 2021-07-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_order', '0005_auto_20210726_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingorderinfo',
            old_name='is_default_address',
            new_name='is_default_delete',
        ),
    ]
