# Generated by Django 3.2.5 on 2021-07-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_order', '0006_rename_is_default_address_shoppingorderinfo_is_default_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingorderinfo',
            name='is_trade',
            field=models.IntegerField(choices=[(0, '已接收'), (1, '未接收')], default=0, verbose_name='是否收到货, 1 已接收 2 未接收'),
        ),
    ]
