# Generated by Django 3.2.5 on 2021-07-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_order', '0007_alter_shoppingorderinfo_is_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingorderinfo',
            name='trade_money',
            field=models.IntegerField(default=0, verbose_name='支付金额'),
        ),
    ]
