# Generated by Django 3.2.5 on 2021-07-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_order', '0009_auto_20210728_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingorderinfo',
            old_name='is_default_delete',
            new_name='delete_order',
        ),
        migrations.AddField(
            model_name='shoppingorderdetail',
            name='delete_shop',
            field=models.IntegerField(choices=[(0, '不删除'), (1, '删除')], default=0, verbose_name='是否删除订单信息，1 删除 ， 0不删除'),
        ),
        migrations.AlterField(
            model_name='shoppingorderdetail',
            name='is_trade',
            field=models.IntegerField(choices=[(0, '未接收'), (1, '已接收')], default=0, verbose_name='该商品是否收货, 0 未接收 1 已接收'),
        ),
    ]
